<html>
    <head>
        <meta charset="utf-8">
    </head>
<body>
    <!-- Affichage du message concaténer à l'aide de deux commande echo -->
    <?php echo $lastname; ?>
    <?php echo $name; ?>

    <!-- Affichage du message concaténer à l'aide d'une commande echo en une chaîne de caractère -->
    <?php echo "$lastname $name"; ?>

    <!-- Affichage du message concaténer à l'aide d'une commande echo avec le point de concaténation -->
    <?php echo $lastname. " " .$name; ?> 
</body>
</html>