<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#id</th>
        <th scope="col">Visible</th>
        <th scope="col">Date</th>
        <th scope="col">Nom du produit</th>
        <th scope="col">Auteur</th>
        <th scope="col">Commentaire</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($ci as $product): ?>
        <tr>
            <th scope="row"><?=$product['product_id'];?></th>
            <td><?=$product['name'];?></td>
            <td><?=$product['shop_name'];?></td>
            <td><?=$product['label'];?></td>
            <td>
                <a href="admin_edit_product.php?id=<?=$product['product_id'];?>" title="Modifier"><i class="far fa-edit"></i></a>
                <a href="admin_remove_product.php?id=<?=$product['product_id'];?>" title="Supprimer"><i class="far fa-trash-alt"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>