<!-- Messages d'erreurs --> 
<?php if (isset($errors) && !empty($errors)): ?>
    <?php foreach ($errors as $error): ?>
        <p class="alert alert-danger"><?=$error;?></p>
    <?php endforeach; ?>
<?php endif; ?>

<form action="admin_edit_product.php" method="POST">
    <input type="hidden" name="product-id" value="<?=$product['product_id'];?>">
    <fieldset>
        <legend>Modifier un produit</legend>
        <div class="form-group">
            <label for="name">Nom du produit</label>
            <input required type="text" class="form-control" id="name" name="name" value="<?=$_POST['name']??$product['name'];?>">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea required name="description" id="description"><?=$_POST['description']??$product['description'];?></textarea>
        </div>
        <div class="form-group">
            <label for="picture">Image</label>
            <input type="text" class="form-control" id="picture" name="picture" value="<?=$_POST['picture']??$product['picture'];?>">
        </div>
        <div class="form-group">
            <label for="price">Prix</label>
            <input required type="number" min="0" step="0.01" class="form-control" id="price" name="price" value="<?=$_POST['price']??$product['price'];?>">
        </div>
        <div class="form-group">
            <label for="stock">Stock</label>
            <input required type="number" min="0" class="form-control" id="stock" name="stock" value="<?=$_POST['stock']??$product['stock'];?>">
        </div>
        <div class="form-group">
            <label for="category">Catégorie</label>
            <select name="category" required>
                <?php foreach ($categories as $category): ?>
                    <?php $categoryId = $_POST['category']??$product['category_id']; ?>
                    <?php $selected = $category['id'] == $categoryId ? 'selected' : ''; ?>
                    <option <?=$selected;?> value="<?=$category['id'];?>"><?=$category['label'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group">
            <label for="creator">Créateur</label>
            <select name="creator" required>
                <?php foreach ($creators as $creator): ?>
                    <?php $creatorId = $_POST['creator']??$product['creator_id']; ?>
                    <?php $selected = $creator['id'] == $creatorId ? 'selected' : ''; ?>
                    <option <?=$selected;?> value="<?=$creator['id'];?>"><?=$creator['shop_name'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </fieldset>
    <input type="submit" value="Enregistrer">                 
</form>