<!-- 

    /**********/
       users
    /**********/

    * id (clé primaire) INT INDEX PRIMARY AI
    * email VARCHAR 100 INDEX UNIQUE
    * password VARCHAR 100
    * firstname VARCHAR 100
    * lastname VARCHAR 100

-->

<!-- Messages d'erreurs --> 
<?php if (isset($errors) && !empty($errors)): ?>
    <?php foreach ($errors as $error): ?>
        <p class="alert alert-danger"><?=$error;?></p>
    <?php endforeach; ?>
<?php endif; ?>

<!-- Formulaire de création de compte client --> 
<form action="create_account.php" method="POST">
  <div class="form-group">
    <label for="firstname">Prénom</label>
    <input required type="text" class="form-control" id="firstname" name="firstname" value="<?=$firstname??'';?>">
  </div>
  <div class="form-group">
    <label for="lastname">Nom</label>
    <input required type="text" class="form-control" id="lastname" name="lastname" value="<?=$lastname??'';?>">
  </div>
  <div class="form-group">
    <label for="email">Email</label>
    <input required type="email" class="form-control" id="email" name="email" value="<?=$email??'';?>">
</div>
  <div class="form-group">
    <label for="password">Mot de passe</label>
    <input minlength="8" required type="password" class="form-control" id="password" name="password">
  </div>
  <div class="form-group">
    <label for="password-confirm">Mot de passe (confirmation)</label>
    <input minlength="8" required type="password" class="form-control" id="password-confirm" name="password-confirm">
  </div>
  <button type="submit" class="btn btn-primary mb-3">Enregistrer</button>
</form>