<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
<body>
    <header>
    <h1>Calcul sur les variables</h1>
    </header>
    <main>
    <!-- Affichage du resultat du calcul des variables "$ht" et "$ttc" et de leurs types -->
        <p><?php echo "Le montant HT est égal à $ht et est de type " .gettype($ht); ?></p>
        <p><?php echo "Le montant TTC est égal à $ttc et est de type " .gettype($ttc); ?></p>
        
    <!-- Affichage du type des variables "price", "tva", et "number" -->
        <p><?php echo "La variable 'price' est de type " .gettype($price); ?></p>
        <p><?php echo "La variable 'tva' est de type " .gettype($tva); ?></p>
        <p><?php echo "La variable 'number' est de type " .gettype($number); ?></p>
    </main>
</body>
</html>